package:
  name: neuroproof 
  version: "1.2.1"
  
source:
  git_url: https://github.com/janelia-flyem/NeuroProof
  git_tag: HEAD

build:
  {% set build_num = 0 %}
  number: {{ build_num }}
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{build_num}}_g{{GIT_FULL_HASH[:7]}}
  detect_binary_files_with_prefix: true # (defaults to false)

requirements:
  build:
    - gcc 4.8.5
    - python 2.7*
    - numpy {{NPY_VER}}*
    - jsoncpp
    - vigra
    - libdvid-cpp
    - vtk         5.10.1.99
    - hdf5        1.8.14
    - qt          4.8.6.99 # [osx]
    - qt          4.8*     # [linux]
    - opencv      2.4.10.1
    
  run:
    - libgcc
    - python 2.7*
    - numpy {{NPY_VER}}*
    - jsoncpp
    - vigra
    - libdvid-cpp
    - vtk         5.10.1.99
    - hdf5        1.8.14
    - qt          4.8.6.99 # [osx]
    - qt          4.8*     # [linux]
    - opencv      2.4.10.1

about:
  home: http://github.com/janelia-flyem/NeuroProof
  license: BSD (3-clause)
  summary: C++ library for image segmentation and analysis 
