package:
  name: ilastik-meta
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/ilastik/ilastik-meta
  git_tag: 1.1.9rc2

build:
  number: 0
  string: 0_{{ environ.get('GIT_BUILD_STR', '') }}

requirements:
  build:
    - python
  run:
    - python
