package:
  name: armadillo
  version: "4.000.2"

source:
  fn: armadillo-4.000.2.tar.gz
  url: http://downloads.sourceforge.net/project/arma/armadillo-4.000.2.tar.gz
  md5: b2891c7b59b96337c154c5d961fd40fb

  patches:
    - patches/use_atlas_lapack.diff

build:
  number: 5
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - openblas # [linux]
  run:
    - libgcc
    - openblas # [linux]


about:
  home: http://arma.sourceforge.net
  license: MIT
  summary: Armadillo C++ Linear Algebra library
