package:
    name: pgmlink-no-ilp
    version: "1.3"

source:
    git_url: https://github.com/ilastik/pgmlink
    git_tag: no-ilp

build:
  number: 0

  #
  # You must build this recipe using 'conda build --numpy=X.Y'
  #
  string: np{{np}}py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

  detect_binary_files_with_prefix: true

requirements:
  build:
    - libgcc
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - patchelf # [linux]
    - dpct
    - ann
    - boost 1.55.0
    - python {{PY_VER}}*
    - numpy >=1.9,{{NPY_VER}}*
    - vigra 1.10*
    - opengm-structured-learning
    - mlpack
    - lemon
    - libxml2
    - dlib
    - libpng 1.6.17
    - armadillo 6.500.5
    - openblas # [linux]

  run:
    - libgcc
    - patchelf # [linux]
    - dpct
    - ann
    - boost 1.55.0
    - python {{PY_VER}}*
    - numpy  {{NPY_VER}}*
    - vigra 1.10*
    - mlpack
    - lemon
    - libpng 1.6.17
    - libxml2
    - dlib
    - armadillo 6.500.5
    - openblas # [linux]

test:
  imports:
    - pgmlink-no-ilp

about:
    home: https://github.com/ilastik/pgmlink
    license: GNU General Public License (GPL)
    summary: 'pgmLink - A Tracking-by-Assignment Software'
